name: Make release
on: [push]
jobs:
  create-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x ../../ci/createTicket.sh
          ../../ci/createTicket.sh