name: Make release
on:
  push:
    tags:
      - '*'
jobs:
  create-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create ticket
        run: sh ./ci/createTicket.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          OrganizationId: ${{ secrets.OrganizationId }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages
        run: npm install --silent

      - name: Run tests
        run: sh ./ci/autotests.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          OrganizationId: ${{ secrets.OrganizationId }}

      - name: Build image
        run: sh ./ci/docker.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          OrganizationId: ${{ secrets.OrganizationId }}